name: CI/CD Pipeline
on: [  workflow_dispatch,push]

env:
  businessGroup: ${{ secrets.BUSINESS_GROUP }}
jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    with:
      businessGroupId: $businessGroup
